import brick1 from "../assets/brick1.png";
import brick2 from "../assets/brick2.png";
import brick3 from "../assets/brick3.png";
import brick4 from "../assets/brick4.png";
import brick5 from "../assets/brick5.png";
import brick6 from "../assets/brick6.png";
import brick7 from "../assets/brick7.png";
import brick8 from "../assets/brick8.png";
import brick9 from "../assets/brick9.png";
import brick10 from "../assets/brick10.png";
import brick11 from "../assets/brick11.png";
import brick12 from "../assets/brick12.png";

import cert1 from "../assets/cert/cert1.jpeg";
import cert2 from "../assets/cert/cert2.jpeg";
import cert3 from "../assets/cert/cert3.jpeg";
import cert4 from "../assets/cert/cert4.jpeg";
import cert5 from "../assets/cert/cert5.jpeg";
import cert6 from "../assets/cert/cert6.jpeg";
import cert7 from "../assets/cert/cert7.jpeg";
import cert8 from "../assets/cert/cert8.jpeg";

// ======= new products image list
import newBrick1 from "../assets/bricks/brick-1.png";
import newBrick2 from "../assets/bricks/brick-2.png";
import newBrick3 from "../assets/bricks/brick-3.png";
import newBrick4 from "../assets/bricks/brick-4.png";
import newBrick5 from "../assets/bricks/brick-5.png";
import newBrick6 from "../assets/bricks/brick-6.png";
import newBrick7 from "../assets/bricks/brick-7.png";
import newBrick8 from "../assets/bricks/brick-8.png";
import newBrick9 from "../assets/bricks/brick-9.png";
import newBrick10 from "../assets/bricks/brick-10.png";
import newBrick11 from "../assets/bricks/brick-11.png";

export const products = [
  {
    id: 1,
    name: "بلوك خفيف 3 فتحة ",
    size: "مقاس 20×20×40",
    price: "1.8",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: brick1,
    code: "30010005",
  },
  {
    id: 2,
    name: "بلوك خفيف 3 فتحة ",
    size: "مقاس 15×20×40",
    price: "1.7",
    type: "مفرغ",
    use: "يستخدم فى الواجهات الجانبية",
    image: brick2,
    code: "30010003",
  },
  {
    id: 3,
    name: "بلوك خفيف 3 فتحة ",
    size: "مقاس 10×20×40",
    price: "1.7",
    type: "مفرغ",
    use: "يستخدم فى المبانى الداخلية والضيقة",
    image: brick3,
    code: "30010001",
  },
  {
    id: 4,
    name: "بلوك خفيف  ",
    size: "مقاس 20×20×40",
    price: "3.1",
    type: "معزول أبيض",
    use: "يستخدم فى الحوائط العازلة للحرارة",
    image: brick4,
    code: "30010007",
  },
  {
    id: 5,
    name: "بلوك خفيف ",
    size: "مقاس 20×20×40",
    price: "4.4",
    type: "معزول أزرق",
    use: "يستخدم فى الحوائط العازلة للحرارة",
    image: brick5,
    code: "30010008",
  },
  {
    id: 6,
    name: "بلوك خفيف ",
    size: "مقاس 10×20×40",
    price: "2.8",
    type: "مسمط",
    use: "يستخدم فى الفواصل الداخلية",
    image: brick6,
    code: "30010017",
  },
  {
    id: 7,
    name: "بلوك خفيف 8 فتحة",
    size: "مقاس 20×20×40",
    price: "2.1",
    type: "مفرغ",
    use: "يستخدم فى الحوائط الحاملة",
    image: brick7,
    code: "30010011",
  },
  {
    id: 8,
    name: "بلوك ثقيل ",
    size: "مقاس 20×20×40",
    price: "3.7",
    type: "مضلع أبيض",
    use: "يستخدم فى المبانى الخارجية",
    image: brick8,
    code: "30010013",
    gur: true,
  },
  {
    id: 9,
    name: "بلوك حرف U",
    size: "مقاس 20×20×40",
    price: "3.5",
    type: "مفرغ",
    use: "يستخدم فى تمديدات السباكة",
    image: brick9,
    code: "30010015",
  },
];
// export const productsPage = [
//   {
//     id: 1,
//     name: "بلوك خفيف 3 فتحة ",
//     size: "مقاس 20×20×40",
//     price: "1.8",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: brick1,
//     code: "30010005",
//   },
//   {
//     id: 2,
//     name: "بلوك خفيف 3 فتحة ",
//     size: "مقاس 15×20×40",
//     price: "1.7",
//     type: "مفرغ",
//     use: "يستخدم فى الواجهات الجانبية",
//     image: brick2,
//     code: "30010003",
//   },
//   {
//     id: 3,
//     name: "بلوك  خفيف 3 فتحة ",
//     size: "مقاس 10×20×40",
//     price: "1.7",
//     type: "مفرغ",
//     use: "يستخدم فى المبانى الداخلية والضيقة",
//     image: brick3,
//     code: "30010001",
//   },
//   {
//     id: 4,
//     name: "بلوك خفيف  ",
//     size: "مقاس 20×20×40",
//     price: "3.1",
//     type: "معزول أبيض",
//     use: "يستخدم فى الحوائط العازلة للحرارة",
//     image: brick4,
//     code: "30010007",
//   },
//   {
//     id: 5,
//     name: "بلوك خفيف ",
//     size: "مقاس 20×20×40",
//     price: "4.4",
//     type: "معزول أزرق",
//     use: "يستخدم فى الحوائط العازلة للحرارة",
//     image: brick5,
//     code: "30010008",
//   },
//   {
//     id: 6,
//     name: "بلوك خفيف ",
//     size: "مقاس 10×20×40",
//     price: "2.8",
//     type: "مسمط",
//     use: "يستخدم فى الفواصل الداخلية",
//     image: brick6,
//     code: "30010017",
//   },
//   {
//     id: 7,
//     name: "بلوك خفيف 8 فتحة",
//     size: "مقاس 20×20×40",
//     price: "2.1",
//     type: "مفرغ",
//     use: "يستخدم فى الحوائط الحاملة",
//     image: brick7,
//     code: "30010011",
//   },
//   {
//     id: 8,
//     name: "بلوك ثقيل ",
//     size: "مقاس 20×20×40",
//     price: "3.7",
//     type: "مضلع أبيض",
//     use: "يستخدم فى المبانى الخارجية",
//     image: brick8,
//     code: "30010013",
//     gur: true,
//   },
//   {
//     id: 9,
//     name: "بلوك حرف U",
//     size: "مقاس 20×20×40",
//     price: "3.5",
//     type: "مفرغ",
//     use: "يستخدم فى تمديدات السباكة",
//     image: brick9,
//     code: "30010015",
//   },
//   {
//     id: 10,
//     name: "بلوك ثقيل 3 فتحة ",
//     size: "مقاس 10×20×40",
//     price: "1.4",
//     type: "مفرغ",
//     use: "يستخدم فى العوازل والسباكة المدفونة",
//     image: brick1,
//     code: "30010002",
//     gur: true,
//   },
//   {
//     id: 11,
//     name: "بلوك ثقيل 3 فتحة ",
//     size: "مقاس 15×20×40",
//     price: "1.4",
//     type: "مفرغ",
//     use: "يستخدم فى عوازل الثلاجات",
//     image: brick2,
//     code: "30010004",
//     gur: true,
//   },
//   {
//     id: 12,
//     name: "بلوك ثقيل 3 فتحة ",
//     size: "مقاس 20×20×40",
//     price: "1.5",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والأسوار",
//     image: brick3,
//     code: "30010006",
//     gur: true,
//   },
//   {
//     id: 13,
//     name: "بلوك ثقيل  ",
//     size: "مقاس 20×20×40",
//     price: "2.4",
//     type: "معزول أبيض",
//     use: "يستخدم فى الحوائط العازلة للحرارة",
//     image: brick4,
//     code: "30010009",
//     gur: true,
//   },
//   {
//     id: 14,
//     name: "بلوك ثقيل ",
//     size: "مقاس 20×20×40",
//     price: "4",
//     type: "معزول أزرق",
//     use: "يستخدم فى المبانى الخارجية",
//     image: brick5,
//     code: "30010016",
//     gur: true,
//   },
//   {
//     id: 15,
//     name: "بلوك ثقيل ",
//     size: "مقاس 10×20×40",
//     price: "2.2",
//     type: "مسمط",
//     use: "يستخدم فى الواجهات والأحمال الثقيلة",
//     image: brick6,
//     code: "30010010",
//     gur: true,
//   },
//   {
//     id: 16,
//     name: "بلوك ثقيل 8 فتحة",
//     size: "مقاس 20×20×40",
//     price: "1.8",
//     type: "مفرغ",
//     use: "يستخدم فى الخزانات الأرضية",
//     image: brick7,
//     code: "30010012",
//     gur: true,
//   },
//   {
//     id: 17,
//     name: "بلوك ثقيل ",
//     size: "مقاس 20×20×40",
//     price: "3",
//     type: "مسمط",
//     use: "يستخدم في الخزانات والبيارات",
//     image: brick10,
//     code: "30010021",
//     gur: true,
//   },
//   {
//     id: 18,
//     name: "بلوك ثقيل 3 فتحة",
//     size: "مقاس 25×20×40",
//     price: "2.9",
//     type: "مفرغ",
//     use: "يستخدم فى القواعد",
//     image: brick11,
//     code: "30010020",
//     gur: true,
//   },
//   {
//     id: 19,
//     name: "بلوك خفيف",
//     size: "مقاس 20×20×40",
//     price: "3.2",
//     type: "مسمط",
//     use: "يستخدم في حلوق الابواب والشبابيك والخزانات",
//     image: brick10,
//     code: "30010018",
//   },
//   {
//     id: 20,
//     name: "بلوك خفيف",
//     size: "مقاس 20×20×40",
//     price: "4.5",
//     type: "مضلع أزرق",
//     use: "يستخدم فى القواعد",
//     image: brick12,
//     code: "30010019",
//   },
// ];
export const productsDiscount = [
  {
    id: 1,
    name: "بلوك خفيف 3 فتحة ",
    size: "مقاس 20×20×40",
    price: "1885",
    sale: "1600",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: brick1,
    code: "30010005",
  },
  {
    id: 2,
    name: "بلوك خفيف 3 فتحة ",
    size: "مقاس 15×20×40",
    price: "1765",
    sale: "1500",
    type: "مفرغ",
    use: "يستخدم فى الواجهات الجانبية",
    image: brick2,
    code: "30010003",
  },
  {
    id: 3,
    name: "بلوك خفيف 3 فتحة ",
    size: "مقاس 10×20×40",
    price: "1765",
    sale: "1500",
    type: "مفرغ",
    use: "يستخدم فى المبانى الداخلية والضيقة",
    image: brick3,
    code: "30010001",
  },
  {
    id: 4,
    name: "بلوك خفيف  ",
    size: "مقاس 20×20×40",
    price: "3120",
    sale: "2560",
    type: "معزول أبيض",
    use: "يستخدم فى الحوائط العازلة للحرارة",
    image: brick4,
    code: "30010007",
  },
  {
    id: 5,
    name: "بلوك خفيف ",
    size: "مقاس 20×20×40",
    price: "4400",
    sale: "3740",
    type: "معزول أزرق",
    use: "يستخدم فى الحوائط العازلة للحرارة",
    image: brick5,
    code: "30010008",
  },
  {
    id: 6,
    name: "بلوك خفيف ",
    size: "مقاس 10×20×40",
    price: "2885",
    sale: "2450",
    type: "مسمط",
    use: "يستخدم فى الفواصل الداخلية",
    image: brick6,
    code: "30010017",
  },
  {
    id: 7,
    name: "بلوك خفيف 8 فتحة",
    size: "مقاس 20×20×40",
    price: "2180",
    sale: "1850",
    type: "مفرغ",
    use: "يستخدم فى الحوائط الحاملة",
    image: brick7,
    code: "30010011",
  },
  {
    id: 8,
    name: "بلوك ثقيل ",
    size: "مقاس 20×20×40",
    price: "3765",
    sale: "3200",
    type: "مضلع أبيض",
    use: "يستخدم فى المبانى الخارجية",
    image: brick8,
    code: "30010013",
    gur: true,
  },
  {
    id: 9,
    name: " بلوك حرف U",
    size: "مقاس 20×20×40",
    price: "3550",
    sale: "3100",
    type: "مفرغ",
    use: "يستخدم فى تمديدات السباكة",
    image: brick9,
    code: "30010015",
  },
  {
    id: 10,
    name: "بلوك ثقيل 3 فتحة ",
    size: "مقاس 10×20×40",
    price: "1408",
    sale: "1225",
    type: "مفرغ",
    use: "يستخدم فى العوازل والسباكة المدفونة",
    image: brick1,
    code: "30010002",
    gur: true,
  },
  {
    id: 11,
    name: "بلوك ثقيل 3 فتحة ",
    size: "مقاس 15×20×40",
    price: "1408",
    sale: "1225",
    type: "مفرغ",
    use: "يستخدم فى عوازل الثلاجات",
    image: brick2,
    code: "30010004",
    gur: true,
  },
  {
    id: 12,
    name: "بلوك ثقيل 3 فتحة ",
    size: "مقاس 20×20×40",
    price: "1552",
    sale: "1350",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والأسوار",
    image: brick3,
    code: "30010006",
    gur: true,
  },
  {
    id: 13,
    name: "بلوك ثقيل  ",
    size: "مقاس 20×20×40",
    price: "2443",
    sale: "2125",
    type: "معزول أبيض",
    use: "يستخدم فى الحوائط العازلة للحرارة",
    image: brick4,
    code: "30010009",
    gur: true,
  },
  {
    id: 14,
    name: "بلوك ثقيل ",
    size: "مقاس 20×20×40",
    price: "4025",
    sale: "3500",
    type: "معزول أزرق",
    use: "يستخدم فى المبانى الخارجية",
    image: brick5,
    code: "30010016",
    gur: true,
  },
  {
    id: 15,
    name: "بلوك ثقيل ",
    size: "مقاس 10×20×40",
    price: "2295",
    sale: "1950",
    type: "مسمط",
    use: "يستخدم فى الواجهات والأحمال الثقيلة",
    image: brick6,
    code: "30010010",
    gur: true,
  },
  {
    id: 16,
    name: "بلوك ثقيل 8 فتحة",
    size: "مقاس 20×20×40",
    price: "1885",
    sale: "1600",
    type: "مفرغ",
    use: "يستخدم فى الخزانات الأرضية",
    image: brick7,
    code: "30010012",
    gur: true,
  },
  {
    id: 17,
    name: "بلوك ثقيل ",
    size: "مقاس 20×20×40",
    price: "3000",
    sale: "2500",
    type: "مسمط",
    use: "يستخدم في الخزانات والبيارات",
    image: brick10,
    code: "30010021",
    gur: true,
  },
  {
    id: 18,
    name: "بلوك ثقيل 3 فتحة",
    size: "مقاس 25×20×40",
    price: "2990",
    sale: "2600",
    type: "مفرغ",
    use: "يستخدم فى القواعد",
    image: brick11,
    code: "30010020",
    gur: true,
  },
  {
    id: 19,
    name: "بلوك خفيف",
    size: "مقاس 20×20×40",
    price: "3235",
    sale: "2750",
    type: "مسمط",
    use: "يستخدم في حلوق الابواب والشبابيك والخزانات",
    image: brick10,
    code: "30010018",
  },
  {
    id: 20,
    name: "بلوك خفيف",
    size: "مقاس 20×20×40",
    price: "4513",
    sale: "3925",
    type: "مضلع أزرق",
    use: "يستخدم فى القواعد",
    image: brick12,
    code: "30010019",
  },
];

export const productDetails = [
  {
    id: 1,
    name: "بلك بركانى خفيف 3 فتحات ",
    href: "/products/normal",
    image: brick1,
  },
  {
    id: 2,
    name: "بلك  بركانى معزول شريحة أبيض 7 فتحات",
    href: "/products/white",
    image: brick4,
  },
  {
    id: 3,
    name: "بلك  بركانى معزول مشرشر (مضلع)  أزرق",
    href: "/products/blue",
    image: brick10,
  },
  {
    id: 4,
    name: "بلك بركانى خفيف 3 فتحات",
    href: "/products/normal",
    image: brick2,
  },
  {
    id: 5,
    name: "بلك  بركانى معزول شريحة أزرق 7 فتحات",
    href: "/products/blue",
    image: brick12,
  },
  {
    id: 6,
    name: "بلك  بركانى خفيف 3 فتحات",
    href: "/products/normal",
    image: brick3,
  },
  {
    id: 7,
    name: "بلك  بركانى خفيف تمديدات حرف U",
    href: "/products/normal",
    image: brick6,
  },
  {
    id: 8,
    name: "بلك  بركانى معزول شريحة أبيض 7 فتحات",
    href: "/products/white",
    image: brick5,
  },
  {
    id: 9,
    name: "بلك  بركانى معزول شريحة أزرق 5 فتحات",
    href: "/products/blue",
    image: brick11,
  },
  {
    id: 10,
    name: "بلك  بركانى معزول شريحة أبيض 3 فتحات",
    href: "/products/white",
    image: brick7,
  },
  {
    id: 11,
    name: "بلك  بركانى معزول مشرشر (مضلع)  أبيض",
    href: "/products/white",
    image: brick9,
  },
  {
    id: 12,
    name: "بلك  بركانى معزول شريحة أزرق 7 فتحات",
    href: "/products/blue",
    image: brick12,
  },
  {
    id: 13,
    name: "بلك  بركانى معزول شريحة أبيض 7 فتحات",
    href: "/products/white",
    image: brick7,
  },
];

export const quality = [
  {
    id: 1,
    image: cert1,
  },
  {
    id: 2,
    image: cert2,
  },
  {
    id: 3,
    image: cert3,
  },
  {
    id: 4,
    image: cert4,
  },
  {
    id: 5,
    image: cert5,
  },
  {
    id: 6,
    image: cert6,
  },
  {
    id: 7,
    image: cert7,
  },
  {
    id: 8,
    image: cert8,
  },
];

// export const itemsInProductsPage = [
//   {
//     id: 1,
//     name: " بلك بركاني معزول ابيض  ",
//     size: " مقاس 20×40",
//     price: "2.35",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick1,
//     code: "30010005",
//   },
//   {
//     id: 2,
//     name: " بلك بركاني عادي 3 فتحة",
//     size: " مقاس 20×40",
//     price: "1.5",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick2,
//     code: "30010005",
//   },
//   {
//     id: 3,
//     name: " بلك بركاني 8 فتحة  ",
//     size: " مقاس 20×40",
//     price: "1.7",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick3,
//     code: "30010005",
//   },
//   {
//     id: 4,
//     name: " بلك بركاني معزول جفاني ",
//     size: " مقاس 20×40",
//     price: "1.7",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick4,
//     code: "30010005",
//   },
//   {
//     id: 5,
//     name: "بلك بركاني مشرشر عازل ازرق ",
//     size: "مقاس 25×40",
//     price: "4.5",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick5,
//     code: "30010005",
//   },
//   {
//     id: 6,
//     name: "بلك بركاني تمديدات سباكة",
//     size: " مقاس 20×20",
//     price: "2.7",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick6,
//     code: "30010005",
//   },
//   {
//     id: 7,
//     name: "بلك بركاني 3 فتحة ",
//     size: " مقاس 15×40",
//     price: "1.4",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick7,
//     code: "30010005",
//   },
//   {
//     id: 8,
//     name: "بلك بركاني 3 فتحة ",
//     size: "مقاس 10×40",
//     price: "1.4",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick8,
//     code: "30010005",
//   },
//   {
//     id: 9,
//     name: " بلك اسمنتي 3 فتحة  ",
//     size: " مقاس 15×40",
//     price: "1.25",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick7,
//     code: "30010005",
//   },
//   {
//     id: 10,
//     name: " بلك اسمنتي 3 فتحة ",
//     size: "مقاس 10×40",
//     price: "1.25",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick8,
//     code: "30010005",
//   },
//   {
//     id: 11,
//     name: "بلك اسمنتي مسمط   ",
//     size: " مقاس 10×40 ",
//     price: "2.8",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick9,
//     code: "30010005",
//   },
//   {
//     id: 12,
//     name: "بلك اسمنتي 3 فتحة ",
//     size: "مقاس 25×40",
//     price: "2.3",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick10,
//     code: "30010005",
//   },
//   {
//     id: 12,
//     name: "بلك اسمنتي مسمط   ",
//     size: " مقاس 20×40  ",
//     price: "3",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick9,
//     code: "30010005",
//   },
//   {
//     id: 13,
//     name: " بلك اسمنتي مسمط   ",
//     size: " مقاس 15×40",
//     price: "2.9",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick5,
//     code: "30010005",
//   },
//   {
//     id: 14,
//     name: " بلك اسمنتي معزول ابيض ",
//     size: " مقاس 20×40  ",
//     price: "2",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick1,
//     code: "30010005",
//   },
//   {
//     id: 15,
//     name: "بلك اسمنتي عادي 3 فتحة ",
//     size: " مقاس 20×40  ",
//     price: "1.35",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick2,
//     code: "30010005",
//   },
//   {
//     id: 16,
//     name: " بلك اسمنتي معزول جفاني ",
//     size: " مقاس 20×40  ",
//     price: "3",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick5,
//     code: "30010005",
//   },
//   {
//     id: 17,
//     name: "بلك اسمنتي مشرشر عازل ابيض ",
//     size: "  مقاس 25×40  ",
//     price: "4.05",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick11,
//     code: "30010005",
//   },
//   {
//     id: 18,
//     name: " بلك اسمنتي مشرشر عازل ابيض ",
//     size: " مقاس 20×40  ",
//     price: "2.95",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick5,
//     code: "30010005",
//   },
//   {
//     id: 19,
//     name: " بلك اسمنتي 8 فتحة",
//     size: " مقاس 20×40  ",
//     price: "1.5",
//     type: "مفرغ",
//     use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
//     image: newBrick11,
//     code: "30010005",
//   },
// ];

export const homePageProducts = [
  {
    id: 1,
    name: " بلك بركاني عادي 3 فتحة",
    size: " مقاس 20×40",
    price: "1.55",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick2,
    code: "30010005",
    bg: "bg-orange-500",
  },
  {
    id: 2,
    name: " بلك بركاني معزول جفاني ",
    size: " مقاس 20×40",
    price: "3.8",
    type: "مفرغ",
    use: "يستخدم فى الفواصل الداخلية",
    image: newBrick4,
    code: "30010005",
    bg: "bg-orange-500",
  },
  {
    id: 3,
    name: " بلك بركاني معزول ابيض  ",
    size: " مقاس 20×40",
    price: "2.3",
    type: "مفرغ",
    use: "يستخدم فى الفواصل الداخلية",
    image: newBrick1,
    code: "30010005",
    bg: "bg-orange-500",
  },
  {
    id: 4,
    name: " بلك بركاني 8 فتحة  ",
    size: " مقاس 20×40",
    price: "1.85",
    type: "مفرغ",
    use: "يستخدم فى الحوائط الحاملة",
    image: newBrick3,
    code: "30010005",
    bg: "bg-orange-500",
  },
  {
    id: 5,
    name: " بلك بركاني تمديدات سباكة ",
    size: " مقاس 20×20",
    price: "3",
    type: "مفرغ",
    use: "يستخدم فى تمديدات السباكة",
    image: newBrick6,
    code: "30010005",
    bg: "bg-orange-500",
  },
  {
    id: 6,
    name: "بلك بركاني مشرشر عازل ازرق ",
    size: "مقاس 25×40",
    price: "5.05",
    type: "مفرغ",
    use: "يستخدم فى الفواصل الداخلية",
    image: newBrick5,
    code: "30010005",
    bg: "bg-orange-500",
  },
  {
    id: 7,
    name: "بلك بركاني 3 فتحة ",
    size: "مقاس 10×40",
    price: "1.45",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick8,
    code: "30010005",
    bg: "bg-orange-500",
  },
  {
    id: 8,
    name: "بلك بركاني 3 فتحة ",
    size: " مقاس 15×40",
    price: "1.5",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick7,
    code: "30010005",
    bg: "bg-orange-500",
  },
  {
    id: 9,
    name: " بلك اسمنتي 3 فتحة ",
    size: "مقاس 10×40",
    price: "1.2",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick8,
    code: "30010005",
    bg: "bg-blue-300",
  },
  {
    id: 10,
    name: " بلك اسمنتي 3 فتحة  ",
    size: " مقاس 15×40",
    price: "1.25",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick7,
    code: "30010005",
    bg: "bg-blue-300",
  },
  {
    id: 11,
    name: "بلك اسمنتي 3 فتحة ",
    size: "مقاس 25×40",
    price: "2.9",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick10,
    code: "30010005",
    bg: "bg-blue-300",
  },
  {
    id: 12,
    name: "بلك اسمنتي مسمط   ",
    size: " مقاس 10×40 ",
    price: "2.185",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick9,
    code: "30010005",
    bg: "bg-blue-300",
  },
  {
    id: 13,
    name: " بلك اسمنتي مسمط   ",
    size: " مقاس 15×40",
    price: "2.875",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick5,
    code: "30010005",
    bg: "bg-blue-300",
  },
  {
    id: 14,
    name: "بلك اسمنتي مسمط   ",
    size: " مقاس 20×40  ",
    price: "3.02",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick9,
    code: "30010005",
    bg: "bg-blue-300",
  },
  {
    id: 15,
    name: "بلك اسمنتي عادي 3 فتحة ",
    size: " مقاس 20×40  ",
    price: "1.3",
    type: "مفرغ",
    use: "يستخدم فى الواجهات الجانبية",
    image: newBrick2,
    code: "30010005",
    bg: "bg-blue-300",
  },
  {
    id: 16,
    name: " بلك اسمنتي معزول ابيض ",
    size: " مقاس 20×40  ",
    price: "2.3",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick1,
    code: "30010005",
    bg: "bg-blue-300",
  },
  {
    id: 17,
    name: "بلك اسمنتي مشرشر عازل ابيض ",
    size: "  مقاس 25×40  ",
    price: "4.05",
    type: "مفرغ",
    use: "يستخدم فى الفواصل الداخلية",
    image: newBrick11,
    code: "30010005",
    bg: "bg-blue-300",
  },
  {
    id: 18,
    name: " بلك اسمنتي معزول جفاني ",
    size: " مقاس 20×40  ",
    price: "3.8",
    type: "مفرغ",
    use: "يستخدم فى الفواصل الداخلية",
    image: newBrick5,
    code: "30010005",
    bg: "bg-blue-300",
  },
  {
    id: 19,
    name: " بلك اسمنتي 8 فتحة",
    size: " مقاس 20×40  ",
    price: "1.6",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick11,
    code: "30010005",
    bg: "bg-blue-300",
  },
  {
    id: 20,
    name: " بلك اسمنتي مشرشر عازل ابيض ",
    size: " مقاس 20×40  ",
    price: "3",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick5,
    code: "30010005",
    bg: "bg-blue-300",
  },
];

export const productsPage = [
  {
    id: 1,
    name: " بلك بركاني عادي 3 فتحة",
    size: " مقاس 20×40",
    price: "1.55",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick2,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 2,
    name: " بلك بركاني معزول جفاني ",
    size: " مقاس 20×40",
    price: "3.8",
    type: "مفرغ",
    use: "يستخدم فى الفواصل الداخلية",
    image: newBrick4,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 3,
    name: " بلك بركاني معزول ابيض  ",
    size: " مقاس 20×40",
    price: "2.3",
    type: "مفرغ",
    use: "يستخدم فى الفواصل الداخلية",
    image: newBrick1,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 4,
    name: " بلك بركاني 8 فتحة  ",
    size: " مقاس 20×40",
    price: "1.85",
    type: "مفرغ",
    use: "يستخدم فى الحوائط الحاملة",
    image: newBrick3,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 5,
    name: " بلك بركاني تمديدات سباكة ",
    size: " مقاس 20×20",
    price: "3",
    type: "مفرغ",
    use: "يستخدم فى تمديدات السباكة",
    image: newBrick6,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 6,
    name: "بلك بركاني مشرشر عازل ازرق ",
    size: "مقاس 25×40",
    price: "5.05",
    type: "مفرغ",
    use: "يستخدم فى الفواصل الداخلية",
    image: newBrick5,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 7,
    name: "بلك بركاني 3 فتحة ",
    size: "مقاس 10×40",
    price: "1.45",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick8,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 8,
    name: "بلك بركاني 3 فتحة ",
    size: " مقاس 15×40",
    price: "1.5",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick7,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 9,
    name: " بلك اسمنتي 3 فتحة ",
    size: "مقاس 10×40",
    price: "1.2",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick8,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 10,
    name: " بلك اسمنتي 3 فتحة  ",
    size: " مقاس 15×40",
    price: "1.25",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick7,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 11,
    name: "بلك اسمنتي 3 فتحة ",
    size: "مقاس 25×40",
    price: "2.9",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick10,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 12,
    name: "بلك اسمنتي مسمط   ",
    size: " مقاس 10×40 ",
    price: "2.185",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick9,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 13,
    name: " بلك اسمنتي مسمط   ",
    size: " مقاس 15×40",
    price: "2.875",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick5,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 14,
    name: "بلك اسمنتي مسمط   ",
    size: " مقاس 20×40  ",
    price: "3.02",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick9,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 15,
    name: "بلك اسمنتي عادي 3 فتحة ",
    size: " مقاس 20×40  ",
    price: "1.3",
    type: "مفرغ",
    use: "يستخدم فى الواجهات الجانبية",
    image: newBrick2,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 16,
    name: " بلك اسمنتي معزول ابيض ",
    size: " مقاس 20×40  ",
    price: "2.3",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick1,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 17,
    name: "بلك اسمنتي مشرشر عازل ابيض ",
    size: "  مقاس 25×40  ",
    price: "4.05",
    type: "مفرغ",
    use: "يستخدم فى الفواصل الداخلية",
    image: newBrick11,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 18,
    name: " بلك اسمنتي معزول جفاني ",
    size: " مقاس 20×40  ",
    price: "3.8",
    type: "مفرغ",
    use: "يستخدم فى الفواصل الداخلية",
    image: newBrick5,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 19,
    name: " بلك اسمنتي 8 فتحة",
    size: " مقاس 20×40  ",
    price: "1.6",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick11,
    code: "30010005",
    bg: "bg-amber-300",
  },
  {
    id: 20,
    name: " بلك اسمنتي مشرشر عازل ابيض ",
    size: " مقاس 20×40  ",
    price: "3",
    type: "مفرغ",
    use: "يستخدم فى تصميم المبانى الداخلية والخارجية",
    image: newBrick5,
    code: "30010005",
    bg: "bg-amber-300",
  },
];
